# EXPLORATION_SBA : 2. Digits Data

In [70]:
# 모듈 import
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

import pandas as pd
import numpy as np

# Data Load
digits = load_digits()
digits_data = digits.data
digits_label = digits.target

digits_df = pd.DataFrame(data = digits_data)

print(digits_df.shape) # 총 1797개의 데이터
print(digits_df.head(1)) # columns = 64, value = 8*8 크기의 이미지 배열 (0~16 사이)

(1797, 64)
    0    1    2     3    4    5    6    7    8    9   ...   54   55   56   57  \
0  0.0  0.0  5.0  13.0  9.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    58    59    60   61   62   63  
0  6.0  13.0  10.0  0.0  0.0  0.0  

[1 rows x 64 columns]


In [54]:
# Target Names 확인
# 이미지 배열 값으로 손글쓰로 쓴 각 숫자를 인식해야한다.
print(digits.target_names)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
# Train, Test 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(digits_data,
                                                   digits_label,
                                                   test_size = 0.3,
                                                   random_state = 31)

In [56]:
#모델 학습

#DecisionTree
from sklearn.tree import DecisionTreeClassifier

d_tree = DecisionTreeClassifier(random_state = 31)

#RandomForest
from sklearn.ensemble import RandomForestClassifier

r_forest = RandomForestClassifier(random_state = 31)

# Support Vector Machine
from sklearn import svm

svm = svm.SVC()

# SGD CLassifier
from sklearn.linear_model import SGDClassifier

sgd = SGDClassifier()

# Logistic Regression
from sklearn.linear_model import LogisticRegression

logistic_r = LogisticRegression()

# 전체 모델 리스트
model_list = [d_tree, r_forest, svm, sgd, logistic_r]

In [71]:
# 모델 학습 & 평가

# 모델 fit & accuracy score를 출력하는 class  

class model_fit_train:
    
    def __init__(self, var):
        self.fit = var.fit(X_train, y_train)
        self.pred = var.predict(X_test)
        
    def accuracy(self):
        print(accuracy_score(y_test, self.pred))
        
    def report(self):
        print(classification_report(y_test, self.pred))
        
    def confusion_matrix(self):
        print(confusion_matrix(y_test, self.pred))

# 모델별 accuracy score 출력        
        
for i in model_list:
    m = model_fit_train(i)
    m.accuracy()

0.8462962962962963
0.975925925925926
0.9888888888888889
0.9314814814814815
0.9555555555555556


/home/theo/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [75]:
# 모델 선택
# accuracy score가 가장 높은 SVM 모델

m = model_fit_train(model_list[2])
m.report()

              precision    recall  f1-score   support

           0       1.00      0.99      0.99        68
           1       0.98      1.00      0.99        55
           2       0.98      1.00      0.99        53
           3       1.00      0.98      0.99        52
           4       0.98      0.97      0.98        61
           5       1.00      1.00      1.00        44
           6       1.00      1.00      1.00        45
           7       1.00      1.00      1.00        58
           8       0.96      0.96      0.96        54
           9       0.98      1.00      0.99        50

    accuracy                           0.99       540
   macro avg       0.99      0.99      0.99       540
weighted avg       0.99      0.99      0.99       540



In [77]:
# confusion_matrix
m.confusion_matrix()

[[67  0  0  0  1  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  0  0]
 [ 0  0 53  0  0  0  0  0  0  0]
 [ 0  0  1 51  0  0  0  0  0  0]
 [ 0  0  0  0 59  0  0  0  2  0]
 [ 0  0  0  0  0 44  0  0  0  0]
 [ 0  0  0  0  0  0 45  0  0  0]
 [ 0  0  0  0  0  0  0 58  0  0]
 [ 0  1  0  0  0  0  0  0 52  1]
 [ 0  0  0  0  0  0  0  0  0 50]]


In [78]:
# 결론: SVM 모델 사용