# EXPLORATION_SBA : 2. Wine Data

In [20]:
# 모듈 import
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

import pandas as pd
import numpy as np

# Data Load
wine = load_wine()
wine_data = wine.data
wine_label = wine.target

wine_df = pd.DataFrame(data = wine_data, columns = wine.feature_names)

print(wine_df.shape) # 총 178개의 데이터
wine_df.head() # columns = 13

(178, 13)


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [21]:
# Feature Names 확인
# 와인별 특성
print(wine.feature_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [22]:
# Target Names 확인
# 와인별 특성 데이터를 기준으로 
print(wine.target_names)

['class_0' 'class_1' 'class_2']


In [42]:
# Train, Test 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(wine_data,
                                                   wine_label,
                                                   test_size = 0.4,
                                                   random_state = 31)

In [43]:
#모델 학습

#DecisionTree
from sklearn.tree import DecisionTreeClassifier

d_tree = DecisionTreeClassifier(random_state = 31)

#RandomForest
from sklearn.ensemble import RandomForestClassifier

r_forest = RandomForestClassifier(random_state = 31)

# Support Vector Machine
from sklearn import svm

svm = svm.SVC()

# SGD CLassifier
from sklearn.linear_model import SGDClassifier

sgd = SGDClassifier()

# Logistic Regression
from sklearn.linear_model import LogisticRegression

logistic_r = LogisticRegression()

# 전체 모델 리스트
model_list = [d_tree, r_forest, svm, sgd, logistic_r]

In [44]:
# 모델 학습 & 평가

# 모델 fit & accuracy score를 출력하는 class  

class model_fit_train:
    
    def __init__(self, var):
        self.fit = var.fit(X_train, y_train)
        self.pred = var.predict(X_test)
        
    def accuracy(self):
        print(accuracy_score(y_test, self.pred))
        
    def report(self):
        print(classification_report(y_test, self.pred))
        
    def confusion_matrix(self):
        print(confusion_matrix(y_test, self.pred))

# 모델별 accuracy score 출력        
        
for i in model_list:
    m = model_fit_train(i)
    m.accuracy()

0.8472222222222222
0.9861111111111112
0.7083333333333334
0.4027777777777778
0.9583333333333334


/home/theo/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [48]:
# 모델 선택
# accuracy score가 가장 높은 RandomForest 모델

m = model_fit_train(model_list[1])
m.report()

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        24
           1       1.00      0.96      0.98        28
           2       1.00      1.00      1.00        20

    accuracy                           0.99        72
   macro avg       0.99      0.99      0.99        72
weighted avg       0.99      0.99      0.99        72



In [49]:
# confusion_matrix
m.confusion_matrix()

[[24  0  0]
 [ 1 27  0]
 [ 0  0 20]]


In [50]:
# 결론: RandomForest 모델 사용